name: Release

on:
  push:
    tags:
      - 'v*'  # Запускается при создании тега версии (v1.0.0, v1.1.0, etc.)
  workflow_dispatch:  # Ручной запуск

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check package
      run: |
        twine check dist/*
        
    - name: Upload to PyPI
      if: github.event_name == 'push' && secrets.PYPI_API_TOKEN != ''
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
        
    - name: PyPI Upload Skipped
      if: github.event_name == 'push' && secrets.PYPI_API_TOKEN == ''
      run: |
        echo "PyPI upload skipped - PYPI_API_TOKEN not configured"
        echo "Package built successfully and available via GitHub Releases"
        echo "To enable PyPI upload:"
        echo "1. Register at https://pypi.org"
        echo "2. Create API token"
        echo "3. Add PYPI_API_TOKEN to GitHub Secrets"
        
    - name: Create GitHub Release
      if: github.event_name == 'push'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
